config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone_number, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name"%>
  </div>

  <div class="field mb-3">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"name@example.com" %>
  </div>

  <div class="field mb-3">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, class:"form-control", placeholder:"phone number" %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="container" style="margin-top: 10em">
	<h1>Editing Friend</h1>

	<%= render 'form', friend: @friend %>

	<%= link_to 'Show', @friend %> |
	<%= link_to 'Back', friends_path %>
</div>

app/views/friends/index.html.erb
<div class="container" style="margin-top: 5em">
<h1>Friends List</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
        <tr>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone_number %></td>
          <td><%= link_to 'Show', friend, class:"btn btn-primary btn-sm" %></td>
          <td><%= link_to 'Edit', edit_friend_path(friend) , class:"btn btn-primary btn-sm" %></td>
          <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Friend', new_friend_path, class: 'btn btn-primary' %>
</div>

app/views/friends/new.html.erb
<div class="container" style="margin-top: 10em">
	<h1>New Friend</h1>

	<%= render 'form', friend: @friend %>

	<%= link_to 'Back', friends_path %>
</div>

app/views/friends/show.html.erb
<div class="container" style="margin-top: 15em">
  <p>
    <h3><strong>First name:</strong></h3><%= @friend.first_name %>
  </p>

  <p>
    <h3><strong>Last name:</strong></h3><%= @friend.last_name %>
  </p>

  <p>
    <h3><strong>Email:</strong></h3><%= @friend.email %>
  </p>

  <p>
    <h3><strong>Phone number:</strong></h3><%= @friend.phone_number %>
  </p>

  <%= link_to 'Edit', edit_friend_path(@friend) %> |
  <%= link_to 'Back', friends_path %>
</div>

app/views/home/index.html.erb
<!--hero header-->
<section class="py-7 py-md-0 bg-hero" id="home">
    <div class="container">
        <div class="row vh-md-100">
            <div class="col-md-8 col-sm-10 col-12 mx-auto my-auto text-center">
                <h1 class="heading-black text-capitalize">Add contacts in seconds using AgendaApp</h1>
                <p class="lead py-3">AgendaApp connects multiple accounts to create an address book for you, the user.</p>

                <li class="btn btn-primary d-inline-flex flex-row align-items-center">
                    <%= link_to "Get Started now", new_user_registration_path, class:"btn btn-primary d-inline-flex flex-row align-items-center" %>
                </li>
            </div>
        </div>
    </div>
</section>

<!-- features section -->
<section class="pt-6 pb-7" id="features">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto text-center">
                <h2 class="heading-black">With AgendaApp you can keep your friends even closer</h2>
                <p class="text-muted lead">Interesting text that exaggerates my ability to create web pages!</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-10 mx-auto">
                <div class="row feature-boxes">
                    <div class="col-md-6 box">
                        <div class="icon-box box-primary">
                            <div class="icon-box-inner">
                                <span data-feather="edit-3" width="35" height="35"></span>
                            </div>
                        </div>
                        <h5>Create once. Share everywhere.</h5>
                        <p class="text-muted">Interesting text that exaggerates my ability to create web pages!</p>
                    </div>
                    <div class="col-md-6 box">
                        <div class="icon-box box-success">
                            <div class="icon-box-inner">
                                <span data-feather="monitor" width="35" height="35"></span>
                            </div>
                        </div>
                        <h5>Unlimited devices</h5>
                        <p class="text-muted">Interesting text that exaggerates my ability to create web pages!</p>
                    </div>
                    <div class="col-md-6 box">
                        <div class="icon-box box-danger">
                            <div class="icon-box-inner">
                                <span data-feather="layout" width="35" height="35"></span>
                            </div>
                        </div>
                        <h5>Beautiful tempates & layouts</h5>
                        <p class="text-muted">Interesting text that exaggerates my ability to create web pages!</p>
                    </div>
                    <div class="col-md-6 box">
                        <div class="icon-box box-info">
                            <div class="icon-box-inner">
                                <span data-feather="globe" width="35" height="35"></span>
                            </div>
                        </div>
                        <h5>Available globally</h5>
                        <p class="text-muted">Interesting text that exaggerates my ability to create web pages!</p>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</section>

<!--faq section-->
<section class="py-7" id="faq">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto text-center">
                <h2>Frequently asked questions</h2>
                <p class="text-muted lead">Answers to most common questions.</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-10 mx-auto">
                <div class="row">
                    <div class="col-md-6 mb-5">
                        <h6>Is this your first application?</h6>
                        <p class="text-muted">This is indeed my first project using Ruby on Rails.</p>
                    </div>
                    <div class="col-md-6 mb-5">
                        <h6>Is this the second most common question?</h6>
                        <p class="text-muted">This is indeed the second most common question and the answer for that is No.</p>
                    </div>
                    <div class="col-md-6 mb-5">
                        <h6>Is this the third most common question?</h6>
                        <p class="text-muted">This is indeed the third most common question and the answer for that is Yes.</p>
                    </div>
                    <div class="col-md-6 mb-5">
                        <h6>Is this the fourth most common question?</h6>
                        <p class="text-muted">This is indeed the fourth most common question and the answer for that is No.</p>
                    </div>
                    <div class="col-md-6 mb-5">
                        <h6>Is this the fifth most common question?</h6>
                        <p class="text-muted">This is indeed the fifth most common question and the answer for that is Yes.</p>
                    </div>
                    <div class="col-md-6 mb-5">
                        <h6>How can I contact you?</h6>
                        <p class="text-muted">Head over to the Contact Me section and ask away!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--Contact me section-->
<section class="py-7" id="contact_me">
	<div class="container">
		<div class="row">
	      <div class="col-md-6 mx-auto">
	        <div class="well well-sm">
	          <form class="form-horizontal" action="" method="post">
	          <fieldset>
	            <legend class="text-center">Contact Me</legend>
	    
	            <!-- Name input-->
	            <div class="form-group">
	              <label class="col-md-10 control-label" for="name">Name</label>
	              <div class="col-md-12">
	                <input id="name" name="name" type="text" placeholder="Your name" class="form-control">
	              </div>
	            </div>
	    
	            <!-- Email input-->
	            <div class="form-group">
	              <label class="col-md-10 control-label" for="email">Your E-mail</label>
	              <div class="col-md-12">
	                <input id="email" name="email" type="text" placeholder="Your email" class="form-control">
	              </div>
	            </div>
	    
	            <!-- Message body -->
	            <div class="form-group">
	              <label class="col-md-10 control-label" for="message">Your message</label>
	              <div class="col-md-12">
	                <textarea class="form-control" id="message" name="message" placeholder="Please enter your message here..." rows="5"></textarea>
	              </div>
	            </div>
	    
	            <!-- Form actions -->
	            <div class="form-group">
	              <div class="col-md-8 text-right">
                    <li class="btn btn-primary d-inline-flex flex-row align-items-center">
                    <%= link_to "Submit", root_path, class:"btn btn-primary d-inline-flex flex-row align-items-center" %>
	              </div>
	            </div>
	          </fieldset>
	          </form>
	        </div>
	      </div>
		</div>
	</div>
</section>

<!--footer-->
<footer class="py-6">
    <div class="container">
        <div class="row">
            <div class="col-sm-5 mr-auto">
                <h5>About Me</h5>
                <p class="text-muted"> My Name is Panagiotis Zazos. I am a diligent and driven graduate Computer Scientist from National and Kapodistrian University of Athens seeking a career that fits my professional skills and personality.</p>
                <ul class="list-inline social social-sm">
                    <li class="list-inline-item">
                        <a href="https://www.facebook.com/pzazos/" target="_blank"><i class="fa fa-facebook" style="font-size: 24px;"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.instagram.com/probablyzazos/" target="_blank"><i class="fa fa-instagram" style="font-size: 24px;"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/zazos"><i class="fa fa-github" target="_blank" style="font-size: 24px;"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.linkedin.com/in/panagiotis-zazos-ba1a02188/" target="_blank" style="font-size: 24px;"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>Legal</h5>
                <ul class="list-unstyled">
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Terms</a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>Partner</h5>
                <ul class="list-unstyled">
                    <li><a href="#">Affiliates</a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>Help</h5>
                <ul class="list-unstyled">
                    <li><a href="#">Support</a></li>
                </ul>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-12 text-muted text-center small-xl">
                &copy; 2019 Knight - All Rights Reserved
            </div>
        </div>
    </div>
</footer>

<!--scroll to top-->
<div class="scroll-top">
    <i class="fa fa-angle-up" aria-hidden="true"></i>
</div>

app/views/layouts/_alerts.html.erb
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= notice %> <a href="#" class="alert-link"></a>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agendapp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Inter UI font-->
    <link href="https://rsms.me/inter/inter-ui.css" rel="stylesheet">

    <!--vendors styles-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">

    <!-- Bootstrap CSS / Color Scheme -->
    <link rel="stylesheet" href="/knight/css/default.css" id="theme-color">


  </head>

  <body id="page-top">
    <%= render "partials/navbar" %>
    <% if notice %>
      <br><br><br>
      <%= render 'layouts/alerts' %>
    <% end %>
    <%= yield %>
  </body>


  <footer>
    <%= render "partials/footer" %>
  </footer>

</html>

app/views/partials/_footer.html.erb
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.7.3/feather.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
<script src="/knight/js/scripts.js"></script>

app/views/partials/_navbar.html.erb
<!--navigation-->
<section class="smart-scroll">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-md navbar-dark">
            <%= link_to 'Agenda App', root_path, class:"navbar-brand heading-black" %>
            <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span data-feather="grid"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
            
                    <% if user_signed_in? %>
                        <li class="nav-item">
                            <%= link_to "Friends List", friends_path, class:"nav-link" %>
                        </li>                    
                        <li class="nav-item">
                            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <%= link_to "Log In", new_user_session_path, class:"nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
                        </li>
                    <% end %>

                    <% if current_page?(root_path) %>
                        <li class="nav-item">
                            <a class="nav-link page-scroll" href="#features">Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link page-scroll" href="#faq">FAQ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link page-scroll" href="#contact_me">Contact Me</a>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <%= link_to "Features", root_path+"#features", class:"nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "FAQ", root_path+"#faq", class:"nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Contact Me", root_path+"#contact_me", class:"nav-link" %>
                        </li>
                    <% end %>
                    
                </ul>
            </div>
        </nav>
    </div>
</section>